spring:
  datasource:
    url: jdbc:mysql://xxx:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    username: root
    password: xxx
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# Mybatis mapper 映射路径配置
mybatis:
type-aliases-package: com.ScanCode.demo.mapper
mapper-locations: classpath*:mapper/*.xml
configLocation: classpath:mybatis-config.xml
